
# Project information
site_name: Dokumentation ZBW Algorithmen und Datenstrukturen
#site_url: 
theme:
  name: material
  features:
    #- navigation.instant
    #- navigation.instant.progress
    #- navigation.tracking
    - navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.sections
    #- navigation.expand
    #- navigation.indexes
    #- toc.follow
    #- toc.integrate
    #- navigation.top
    - content.tabs.link
    - content.code.copy
    - content.action.view
    - content.action.edit
    - search.suggest
    - search.highlight
    - search.share

plugin:
  - search
  - tags
  - awesome-pages
  - git-revision-date-localized:
      enable_creation_date: false
      type: datetime
      format: "%d.%m.%Y"

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - pymdownx.superfences